#!/usr/bin/env python3
"""Generate Apache per-directory rules and a reviewable legacy URL map."""
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://neaist.tecnico.ulisboa.pt"
mapping = json.loads((ROOT / "scripts/legacy-redirects.json").read_text())
pages = json.loads((ROOT / "scripts/seo-pages.json").read_text())
lines = [
    "# Generated by scripts/build_redirects.py. Apache 2.4; see docs/seo/hosting.md.",
    "# True HTTP redirects require AllowOverride on the AFS virtual host.",
    "Options -MultiViews -Indexes", "DirectoryIndex index.html", "ErrorDocument 404 /404.html", "",
    '<FilesMatch "(?i)^(\\.env(?:\\..*)?|config\\.local\\.php|.*\\.(?:sql|log|bak))$">',
    "    Require all denied", "</FilesMatch>", "",
    "<IfModule mod_headers.c>",
    '    <FilesMatch "^(google[0-9a-f]+\\.html|404\\.html)$">',
    '        Header always set X-Robots-Tag "noindex, follow"',
    "    </FilesMatch>", "</IfModule>", "", "<IfModule mod_rewrite.c>", "RewriteEngine On", "",
    "# Development and source files must not be served if accidentally uploaded.",
    "RewriteRule ^(?:\\.git|\\.github|docs|scripts)(?:/|$) - [F,L]", "",
    "# WordPress IDs are mapped BEFORE the index/HTTPS rules (one hop)."
]
for page_id, target in mapping["wordpressIds"].items():
    lines += [f"RewriteCond %{{QUERY_STRING}} (?:^|&)(?:p|page_id)={page_id}(?:\\.html)?(?:&|$) [NC]", f"RewriteRule ^(?:index\\.(?:php|html?))?/?$ {BASE}{target} [R=301,L,QSD,NC]", f"RewriteRule ^index\\.html\\?p={page_id}\\.html$ {BASE}{target} [R=301,L,QSD,NC]"]
lines += ["", "# Unknown WordPress content has no verified replacement; never send it home.", "RewriteCond %{QUERY_STRING} (?:^|&)(?:p|page_id)=[0-9]+(?:\\.html)?(?:&|$) [NC]", "RewriteRule ^(?:index\\.(?:php|html?))?/?$ - [G,L]", "RewriteRule ^index\\.html\\?p=[0-9]+\\.html$ - [G,L,NC]", "", "# Verified legacy routes and documents."]
for row in mapping["paths"]:
    old = row["old"].lstrip("/")
    pattern = re.escape(old.rstrip("/")) + (r"/?" if old.endswith("/") else "")
    # Python escapes spaces; Apache patterns with spaces must be quoted.
    pattern = pattern.replace(r"\ ", " ")
    lines.append(f'RewriteRule "^{pattern}$" {BASE}{row["new"]} [R=301,L,QSD,NC]')
lines += ["", "# Canonical homepage; THE_REQUEST avoids redirecting DirectoryIndex internally.", "RewriteCond %{THE_REQUEST} \\s/+index\\.(?:html?|php)(?:[?\\s/]) [NC]", f"RewriteRule ^index\\.(?:html?|php)/?$ {BASE}/ [R=301,L,NC]", "", "# Known page aliases only: extensionless, trailing slash and case variants."]
for name in pages:
    if name == "index.html": continue
    slug = re.escape(name[:-5])
    lines += [f"RewriteCond %{{REQUEST_URI}} !^/{re.escape(name)}$", f"RewriteRule ^{slug}(?:\\.html)?/?$ {BASE}/{name} [R=301,L,NC]"]
lines += ["", "# Aliases above already include HTTPS, avoiding HTTP -> alias -> canonical chains.", "# The TLS proxy must supply a trusted X-Forwarded-Proto header (see hosting.md).", "RewriteCond %{HTTP_HOST} !^(?:localhost|127\\.0\\.0\\.1)(?::[0-9]+)?$ [NC]", "RewriteCond %{HTTP_HOST} !^neaist\\.tecnico\\.ulisboa\\.pt$ [NC]", f"RewriteRule ^ {BASE}%{{REQUEST_URI}} [R=301,L,NE]", "RewriteCond %{HTTP_HOST} ^neaist\\.tecnico\\.ulisboa\\.pt$ [NC]", "RewriteCond %{HTTPS} !=on", "RewriteCond %{HTTP:X-Forwarded-Proto} !^https$ [NC]", f"RewriteRule ^ {BASE}%{{REQUEST_URI}} [R=301,L,NE]", "</IfModule>", ""]
(ROOT / ".htaccess").write_text("\n".join(lines))
doc = ["# Legacy URL migration map", "", "Source: the migration brief, existing redirects, and the WordPress HTML/REST export beside `new-site/`.", "", "Status below is the **configured** status. See `redirect-verification.json` for actual local Apache HTTP results and `production-before.json` for the production baseline. Rules are not claimed live until post-deployment verification passes.", "", "| Old path | Canonical target | Configured HTTP status | Reason |", "| --- | --- | --- | --- |"]
for row in mapping["paths"]:
    doc.append(f'| `{row["old"]}` | `{BASE}{row["new"]}` | 301 | {row["reason"]} |')
doc += ["", "## WordPress IDs", "", "Each ID is supported as `/?p=ID`, `/?page_id=ID`, `/index.php?p=ID`, `/index.html?p=ID` and the exported `/index.html%3Fp=ID.html` URL, directly to the target below.", "", "| ID | Canonical target | Configured status |", "| --- | --- | --- |"]
for page_id, target in mapping["wordpressIds"].items():
    doc.append(f"| {page_id} | `{BASE}{target}` | 301 |")
doc += ["", "`/index.html`, `/index.htm`, `/index.php` and their case variants consolidate to `/`. Known page extensionless, case and trailing-slash variants consolidate to their existing `.html` routes. Unknown numeric WordPress IDs return 410; unrelated missing URLs, old CSS/JS, feeds and WordPress API endpoints return 404. There is no blanket homepage redirect.", "", "No historical server/access logs are available in the repository. Additional mappings should be added only with evidence of an equivalent destination.", ""]
(ROOT / "docs/seo/legacy-redirects.md").write_text("\n".join(doc))
print(f'Generated {len(mapping["paths"])} path mappings and {len(mapping["wordpressIds"])} WordPress ID mappings.')
